version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server
    environment:
      - NODE_ENV=production

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server/data:/app/data  # JSON
    environment:
      - NODE_ENV=production